// Generated by CoffeeScript 1.8.0
(function() {
  var darkenNavbar, orderImages, scrollToSection;

  $(function() {
    orderImages();
    $(window).on('scroll', darkenNavbar);
    $('.navbar a').on('click', scrollToSection);
    return $('.strategy li').on('click', 'h3', function(e) {
      var $icon, $text;
      $icon = $(e.delegateTarget).find('i');
      if ($icon.hasClass('fa-angle-double-right')) {
        $icon.switchClass('fa-angle-double-right', 'fa-angle-double-down', 100);
      } else {
        $icon.switchClass('fa-angle-double-down', 'fa-angle-double-right', 100);
      }
      $text = $(e.delegateTarget).find('text');
      return $text.toggleClass('hide');
    });
  });

  orderImages = function() {
    return setInterval(function() {
      return $('.image-container:last').prependTo('#intro-container');
    }, 15000);
  };

  darkenNavbar = function(event) {
    var $nav;
    if ($(window).scrollTop() > 200) {
      $nav = $('nav:first');
      return $nav.addClass('scrolled');
    } else {
      $nav = $('nav:first');
      return $nav.removeClass('scrolled');
    }
  };

  scrollToSection = function(event) {
    var target;
    event.preventDefault();
    if (this.hash) {
      target = $(this.hash);
    }
    return $('html, body').animate({
      scrollTop: target.offset().top
    }, 500);
  };

}).call(this);
