function template(locals) {
var jade_debug = [{ lineno: 1, filename: "index.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

jade_debug.unshift({ lineno: 0, filename: "index.jade" });
jade_debug.unshift({ lineno: 1, filename: "index.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "index.jade" });
buf.push("<html>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "index.jade" });
buf.push("<head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "index.jade" });
buf.push("<meta charset=\"UTF-8\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "index.jade" });
buf.push("<title>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("digitalAMP");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "index.jade" });
buf.push("<link rel=\"stylesheet\" href=\"css/vendor/bootstrap.min.css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "index.jade" });
buf.push("<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "index.jade" });
buf.push("<link rel=\"stylesheet\" href=\"css/site.css\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "index.jade" });
buf.push("<body id=\"top\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 10, filename: "index.jade" });
buf.push("<nav class=\"navbar navbar-default navbar-fixed-top not-scrolled\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 11, filename: "index.jade" });
buf.push("<div class=\"navbar-header\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: "index.jade" });
buf.push("<a href=\"#top\" class=\"navbar-brand\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 12, filename: jade_debug[0].filename });
buf.push("digital");
jade_debug.shift();
jade_debug.unshift({ lineno: 13, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 13, filename: jade_debug[0].filename });
buf.push("AMP");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "index.jade" });
buf.push("<ul class=\"nav navbar-nav navbar-right\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: "index.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("<a href=\"#whatwedo\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 15, filename: jade_debug[0].filename });
buf.push("What We Do");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "index.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: jade_debug[0].filename });
buf.push("<a href=\"#strategy\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 16, filename: jade_debug[0].filename });
buf.push("Strategy");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "index.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("<a href=\"#about\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 17, filename: jade_debug[0].filename });
buf.push("About");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "index.jade" });
buf.push("<li>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push("<a href=\"#contact\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 18, filename: jade_debug[0].filename });
buf.push("Contact");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</nav>");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "index.jade" });
buf.push("<section id=\"intro-container\" data-current-index='0' class=\"clearfix\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 21, filename: "index.jade" });
buf.push("<div class=\"image-container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 22, filename: "index.jade" });
buf.push("<div style=\"background-image: url(images/sample1.jpg)\" class=\"image\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 23, filename: "index.jade" });
buf.push("<div class=\"color-overlay\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 24, filename: "index.jade" });
buf.push("<div class=\"image-container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 25, filename: "index.jade" });
buf.push("<div style=\"background-image: url(images/sample2.jpg)\" class=\"image\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 26, filename: "index.jade" });
buf.push("<div class=\"color-overlay\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 27, filename: "index.jade" });
buf.push("<div class=\"image-container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 28, filename: "index.jade" });
buf.push("<div style=\"background-image: url(images/sample3.jpg)\" class=\"image\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 29, filename: "index.jade" });
buf.push("<div class=\"color-overlay\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 30, filename: "index.jade" });
buf.push("<div class=\"image-container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 31, filename: "index.jade" });
buf.push("<div style=\"background-image: url(images/sample4.jpg)\" class=\"image\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 32, filename: "index.jade" });
buf.push("<div class=\"color-overlay\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 34, filename: "index.jade" });
buf.push("<section class=\"main-info-container\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: "index.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 35, filename: jade_debug[0].filename });
buf.push("We are digital");
jade_debug.shift();
jade_debug.unshift({ lineno: 36, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 36, filename: jade_debug[0].filename });
buf.push("AMP");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 37, filename: "index.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 37, filename: jade_debug[0].filename });
buf.push("A turn-key digital solution for your business's web and mobile advertising and marketing needs.");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 39, filename: "index.jade" });
buf.push("<section id=\"whatwedo\" class=\"icons row\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 40, filename: "index.jade" });
buf.push("<h2 id=\"icon-header\" class=\"text-center\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 40, filename: jade_debug[0].filename });
buf.push("What We Do");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 41, filename: "index.jade" });
buf.push("<figure class=\"col-md-4 text-center one\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 42, filename: "index.jade" });
buf.push("<img id=\"adversiting-image\" src=\"images/advertising.svg\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 43, filename: "index.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 44, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 44, filename: jade_debug[0].filename });
buf.push("A");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 45, filename: "index.jade" });
buf.push("dvertising");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 46, filename: "index.jade" });
buf.push("<text>");
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
buf.push("We communicate the right message via search engine optimization,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 46, filename: jade_debug[0].filename });
buf.push("mobile, email, blogs and social media in text and video.");
jade_debug.shift();
jade_debug.shift();
buf.push("</text>");
jade_debug.shift();
jade_debug.shift();
buf.push("</figure>");
jade_debug.shift();
jade_debug.unshift({ lineno: 47, filename: "index.jade" });
buf.push("<figure class=\"col-md-4 text-center two\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 48, filename: "index.jade" });
buf.push("<img id=\"marketing-image\" src=\"images/marketing.svg\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 49, filename: "index.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 50, filename: jade_debug[0].filename });
buf.push("M");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 51, filename: "index.jade" });
buf.push("arketing");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 52, filename: "index.jade" });
buf.push("<text>");
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
buf.push("We create and distribute valuable, relevant and consistent content ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
buf.push("to attract and acquire a clearly defined audience – with the goal ");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 52, filename: jade_debug[0].filename });
buf.push("of driving profitable customer action.");
jade_debug.shift();
jade_debug.shift();
buf.push("</text>");
jade_debug.shift();
jade_debug.shift();
buf.push("</figure>");
jade_debug.shift();
jade_debug.unshift({ lineno: 53, filename: "index.jade" });
buf.push("<figure class=\"col-md-4 text-center three\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 54, filename: "index.jade" });
buf.push("<img id=\"promotion-image\" src=\"images/promotions.svg\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 55, filename: "index.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 55, filename: jade_debug[0].filename });
buf.push(" ");
jade_debug.shift();
jade_debug.unshift({ lineno: 56, filename: "index.jade" });
buf.push("<span>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 56, filename: jade_debug[0].filename });
buf.push("P");
jade_debug.shift();
jade_debug.shift();
buf.push("</span>");
jade_debug.shift();
jade_debug.unshift({ lineno: 57, filename: "index.jade" });
buf.push("romotions");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 58, filename: "index.jade" });
buf.push("<text>");
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
buf.push("We build campaigns around the elements that make your business unique.");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
buf.push("You provide us the tools for your product or service and we do the rest.");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift({ lineno: 58, filename: jade_debug[0].filename });
buf.push("");
jade_debug.shift();
jade_debug.shift();
buf.push("</text>");
jade_debug.shift();
jade_debug.shift();
buf.push("</figure>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift({ lineno: 59, filename: "index.jade" });
buf.push("<section id=\"strategy\" class=\"strategy row\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 61, filename: "index.jade" });
buf.push("<div id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\" class=\"panel-group\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: "index.jade" });
buf.push("<h2>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 62, filename: jade_debug[0].filename });
buf.push("Our Strategy");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 63, filename: "index.jade" });
buf.push("<div class=\"panel panel-default\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 64, filename: "index.jade" });
buf.push("<div role=\"tab\" id=\"headingOne\" class=\"panel-heading\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 65, filename: "index.jade" });
buf.push("<h4 class=\"panel-title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 66, filename: "index.jade" });
buf.push("<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 67, filename: "index.jade" });
buf.push("Collapsible Group Item #1");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 69, filename: "index.jade" });
buf.push("<div id=\"collapseOne\" role=\"tabpanel\" aria-labelledby=\"headingOne\" class=\"panel-collapse collapse in\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 70, filename: "index.jade" });
buf.push("<div class=\"panel-body\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 71, filename: "index.jade" });
buf.push("Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 73, filename: "index.jade" });
buf.push("<div class=\"panel panel-default\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 74, filename: "index.jade" });
buf.push("<div id=\"headingTwo\" role=\"tab\" class=\"panel-heading\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 75, filename: "index.jade" });
buf.push("<h4 class=\"panel-title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 76, filename: "index.jade" });
buf.push("<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\" class=\"collapsed\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 77, filename: "index.jade" });
buf.push("Collapsible Group Item #2");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 79, filename: "index.jade" });
buf.push("<div id=\"collapseTwo\" role=\"tabpanel\" aria-labelledby=\"headingTwo\" class=\"panel-collapse collapse\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 80, filename: "index.jade" });
buf.push("<div class=\"panel-body\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 81, filename: "index.jade" });
buf.push("Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 83, filename: "index.jade" });
buf.push("<div class=\"panel panel-default\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 84, filename: "index.jade" });
buf.push("<div id=\"headingThree\" role=\"tab\" class=\"panel-heading\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 85, filename: "index.jade" });
buf.push("<h4 class=\"panel-title\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 86, filename: "index.jade" });
buf.push("<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\" class=\"collapsed\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 87, filename: "index.jade" });
buf.push("Collapsible Group Item #3");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</h4>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 89, filename: "index.jade" });
buf.push("<div id=\"collapseThree\" role=\"tabpanel\" aria-labelledby=\"headingThree\" class=\"panel-collapse collapse\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 90, filename: "index.jade" });
buf.push("<div class=\"panel-body\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 91, filename: "index.jade" });
buf.push("Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift({ lineno: 94, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 95, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 96, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 97, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 98, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 99, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 100, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 101, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 102, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 103, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 104, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 105, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 106, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 107, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 108, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 109, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 110, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 111, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 112, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 113, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 114, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 115, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 116, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 117, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 118, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 119, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 120, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 121, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 122, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 123, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 124, filename: "index.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 124, filename: "index.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 125, filename: "index.jade" });
buf.push("<div class=\"strategy-image col-md-6\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 126, filename: "index.jade" });
buf.push("<img src=\"images/strategy.png\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.unshift({ lineno: 129, filename: "index.jade" });
buf.push("<script src=\"js/vendor/jquery-1.11.2.min.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 130, filename: "index.jade" });
buf.push("<script src=\"js/vendor/jquery-ui.min.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 131, filename: "index.jade" });
buf.push("<script src=\"js/vendor/bootstrap.min.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 132, filename: "index.jade" });
buf.push("<script src=\"js/site.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\nhtml\n  head\n    meta(charset=\"UTF-8\")\n    title digitalAMP\n    link(rel=\"stylesheet\", href=\"css/vendor/bootstrap.min.css\")\n    link(rel=\"stylesheet\", href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\")\n    link(rel=\"stylesheet\", href=\"css/site.css\")\n  body#top\n    nav.navbar.navbar-default.navbar-fixed-top.not-scrolled\n      .navbar-header\n        a.navbar-brand(href=\"#top\") digital\n          span AMP\n      ul.nav.navbar-nav.navbar-right\n        li: a(href=\"#whatwedo\") What We Do\n        li: a(href=\"#strategy\") Strategy\n        li: a(href=\"#about\") About\n        li: a(href=\"#contact\") Contact\n\n    section#intro-container.clearfix(data-current-index=0)\n      div.image-container\n        div.image(style=\"background-image: url(images/sample1.jpg)\")\n          div.color-overlay\n      div.image-container\n        div.image(style=\"background-image: url(images/sample2.jpg)\")\n          div.color-overlay\n      div.image-container\n        div.image(style=\"background-image: url(images/sample3.jpg)\")\n          div.color-overlay\n      div.image-container\n        div.image(style=\"background-image: url(images/sample4.jpg)\")\n          div.color-overlay\n\n    section.main-info-container\n      h2 We are digital\n        span AMP\n      p A turn-key digital solution for your business's web and mobile advertising and marketing needs.\n\n    section#whatwedo.icons.row\n      h2.text-center#icon-header What We Do\n      figure.col-md-4.text-center.one\n        img#adversiting-image(src=\"images/advertising.svg\")\n        h2\n          span A\n          | dvertising\n        text. \n          We communicate the right message via search engine optimization,\n          mobile, email, blogs and social media in text and video.\n      figure.col-md-4.text-center.two\n        img#marketing-image(src=\"images/marketing.svg\")\n        h2\n          span M\n          | arketing\n        text.\n          We create and distribute valuable, relevant and consistent content \n          to attract and acquire a clearly defined audience – with the goal \n          of driving profitable customer action.\n      figure.col-md-4.text-center.three\n        img#promotion-image(src=\"images/promotions.svg\")\n        h2 \n          span P\n          | romotions\n        text.\n          We build campaigns around the elements that make your business unique.\n          You provide us the tools for your product or service and we do the rest.\n    \n    section#strategy.strategy.row\n\n      div.panel-group#accordion(role=\"tablist\", aria-multiselectable=\"true\")\n        h2 Our Strategy\n        div.panel.panel-default\n          div.panel-heading(role=\"tab\", id=\"headingOne\")\n            h4.panel-title\n              a(data-toggle=\"collapse\", data-parent=\"#accordion\", href=\"#collapseOne\", aria-expanded=\"true\", aria-controls=\"collapseOne\")\n                | Collapsible Group Item #1\n\n          div#collapseOne.panel-collapse.collapse.in(role=\"tabpanel\", aria-labelledby=\"headingOne\")\n            div.panel-body\n              | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\n\n        div.panel.panel-default\n          div.panel-heading#headingTwo(role=\"tab\")\n            h4.panel-title\n              a.collapsed(data-toggle=\"collapse\", data-parent=\"#accordion\", href=\"#collapseTwo\", aria-expanded=\"false\", aria-controls=\"collapseTwo\")\n                | Collapsible Group Item #2\n\n          div#collapseTwo.panel-collapse.collapse(role=\"tabpanel\", aria-labelledby=\"headingTwo\")\n            div.panel-body\n              | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\n\n        div.panel.panel-default\n          div#headingThree.panel-heading(role=\"tab\")\n            h4.panel-title\n              a.collapsed(data-toggle=\"collapse\", data-parent=\"#accordion\", href=\"#collapseThree\", aria-expanded=\"false\", aria-controls=\"collapseThree\")\n                | Collapsible Group Item #3\n\n          div#collapseThree.panel-collapse.collapse(role=\"tabpanel\", aria-labelledby=\"headingThree\")\n            div.panel-body\n              | Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.\n      \n      //- div.content.col-md-6\n      //-   h2 Our Strategy\n      //-   ul\n      //-     li \n      //-       i.fa.fa-angle-double-right\n      //-       h3 Quality\n      //-       text.hide. Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n      //-         sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n      //-         Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris \n      //-         nisi ut aliquip ex ea commodo consequat.\n      //-     li \n      //-       i.fa.fa-angle-double-right\n      //-       h3 Research\n      //-       text.hide. Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n      //-         sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n      //-         Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris \n      //-         nisi ut aliquip ex ea commodo consequat.\n      //-     li \n      //-       i.fa.fa-angle-double-right\n      //-       h3 Language\n      //-       text.hide. Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n      //-         sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n      //-         Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris \n      //-         nisi ut aliquip ex ea commodo consequat.\n      //-     li \n      //-       i.fa.fa-angle-double-right\n      //-       h3 Engagement\n      //-       text.hide. Lorem ipsum dolor sit amet, consectetur adipiscing elit, \n      //-         sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. \n      //-         Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris \n      //-         nisi ut aliquip ex ea commodo consequat.\n            \n      div.strategy-image.col-md-6\n        img(src=\"images/strategy.png\")\n\n    \n  script(src=\"js/vendor/jquery-1.11.2.min.js\")\n  script(src=\"js/vendor/jquery-ui.min.js\")\n  script(src=\"js/vendor/bootstrap.min.js\")\n  script(src=\"js/site.js\")\n");
}
}